n = input('Digite algo: ')
print('o tipo primitivo desse valor é', type(n))
print('Só tem espaços? {}'.format(n.isspace()))
print('É um número? {}'.format(n.isnumeric()))
print('É alfabético? {}'.format(n.isalpha()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Está em maiusculas? {}'.format(n.isupper()))
print('Está em minusculas? {}'.format(n.islower()))
print('Está capitalizada? {}'.format(n.istitle()))
